#!/bin/bash

# Copyright (c) 2018-2021, AT&T Intellectual Property.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

# Traffic class is set to network control (CS6) for kernel-originated ND pkts,
# but need DSCP field to be set for RA originated by radvd as per RFC4594.

ip6tables -t mangle -A POSTROUTING -p ipv6-icmp --icmpv6-type \
router-advertisement -j DSCP --set-dscp-class CS6
