#!/bin/bash
# **** License ****
# Copyright (c) 2019, AT&T Intellectual Property. All rights reserved.
#
# Copyright (c) 2014,2016 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# This code was originally developed by Vyatta, Inc.
# Portions created by Vyatta are Copyright (C) 2011 Vyatta, Inc.
# All Rights Reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Author:       Mohit Mehta <mohit@vyatta.com>
# Description:  Check if the given file is under /config. Used for files that
#               are referenced from the CLI and need to be preserved during
#               image upgrade. Warn the user if these aren't under /config
#
# **** End License ****

FILE=$1
CONFIG_DIR=$2

if [[   ( $FILE =~ ^/config/.*$ ) ||					\
        ( $FILE =~ ^/opt/vyatta/etc/config/.*$ ) ]]; then
        exit 0
else
        echo Warning: \'"$FILE"\' lies outside of "$CONFIG_DIR" directory.	\
             It will not get preserved during image upgrade.
fi
