#! /usr/bin/perl
#
# Copyright (c) 2018-2019, AT&T Intellectual Property. All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#

use strict;
use warnings;
use lib '/opt/vyatta/share/perl5';
use Getopt::Long;
use Vyatta::Config;
use Vyatta::VPlaned;

use vyatta::proto::IP6RedirectsConfig;

my ($action);

sub set_ip6_redirects_action {
    my $cstore = new Vyatta::VPlaned;
    my $cmd = "ip6";

    my $enable_redirects = $action eq 'true' ? 0 : 1;

    my $redirect = IP6RedirectsConfig->new({
	enable_redirects  => $enable_redirects
				     });

    $cstore->store_pb(
	"ip6 redirects",
	$redirect,
	"vyatta:ip6");
}

sub usage {
    print "Usage: $0 [--action=true/false]\n";
    exit 1;
}

GetOptions( 'action=s' => \$action, ) or usage();

set_ip6_redirects_action() if defined( $action );
