#!/bin/bash
# Copyright (c) 2019-2021 AT&T Intellectual Property
# All rights reserved.
# Copyright (c) 2015-2016, 2019 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

progname=${0##*/}
action=$1
[ "$action" != create ]
value=$? # 1 if action is to create config to disable IPv6
intf=$2

param=disable_ipv6
ipv6_conf=/proc/sys/net/ipv6/conf
ipv6_run=/var/run/vyatta
procfile=$ipv6_conf/$intf/$param
runfile=$ipv6_run/ipv6_disable.$intf

create_intf () {
    if [ -e "$procfile" ]; then
        echo $value > "$procfile"
    else
        echo "IPv6 will be disabled when $intf comes up"
    fi
    touch "$runfile"
}

delete_intf () {
    if [ -e "$procfile" ]; then
        # Only re-enable IPv6 per interface if not globally disabled
        global=$(cat $ipv6_conf/default/$param)
        if [ "$global" == "0" ]; then
            if [ -e /sys/class/net/"$intf"/brport ]; then
                echo "$intf not re-enabled as it is in L2 mode"
                return
            else
                echo $value > "$procfile"
                restore-ipv6-address.pl --force-restore "$intf"
            fi
        else
            echo "$intf not re-enabled as IPv6 is globally disabled"
        fi
    else
        echo "IPv6 will be re-enabled when $intf comes up"
    fi
    rm -f "$runfile"
}

if [ -z "$intf" ]; then
       echo "Usage: $progname {create|delete} <ifname>"
       exit 1
fi

case "$action" in
    create)
        create_intf
        ;;
    delete)
        delete_intf
        ;;
    *)
        echo "Usage: $progname {create|delete} <ifname>"
        exit 1
        ;;
esac
