#!/bin/bash
# Copyright (c) 2019, AT&T Intellectual Property. All rights reserved.
#
# Copyright (c) 2015 by Brocade Communications Systems, Inc.
# All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only
#
# Dump all /var/log/messages including compressed files.
#
if ls "$1"/var/log/messages*.gz 1>/dev/null 2>&1; then
    zcat $(printf "%s\n" "$1"/var/log/messages*.gz | sort -nr)
fi
cat "$1"/var/log/messages  
