#!/bin/sh

if [ -f /run/motd.vyatta ] ; then
    cat /run/motd.vyatta
else
    VERSION=$(/opt/vyatta/bin/vyatta-show-version)
    DESC=$(echo "$VERSION" | sed -n 's/^Description:\s*\([^0-9]\+\).*/\1/p')
    echo "Welcome to $DESC"
    echo "$VERSION" | head -2
fi
